name: "Continuous Integration"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  building-linting-testing:
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10.10.0 --activate

      - name: Install Dependencies
        run: pnpm i
    
      - name: Building NestJS
        run: pnpm build

      - name: Biome Linting
        run: pnpm lint

      - name: Testing Unit Tests
        run: pnpm test